image:
  repository: postgres
  tag: "16-alpine"
  pullPolicy: IfNotPresent

auth:
  username: appuser
  password: "please-change-me"   # CHANGE for real use
  database: appdb

service:
  type: ClusterIP
  port: 5432

persistence:
  enabled: false                 # set true later when you install a default StorageClass

livenessProbe:
  tcpSocket: { port: 5432 }
readinessProbe:
  tcpSocket: { port: 5432 }
