# ----- Chart-level knobs the scaffold expects -----
replicaCount: 1

image:
  repository: postgres
  tag: "16-alpine"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""   # let helpers generate the name

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 5432

# Ingress exists only to satisfy scaffold; kept OFF for a DB
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}
#  limits:
#    cpu: 500m
#    memory: 512Mi
#  requests:
#    cpu: 100m
#    memory: 256Mi

# Probes suited for Postgres (TCP on 5432)
livenessProbe:
  tcpSocket:
    port: 5432
  initialDelaySeconds: 20
  periodSeconds: 20
readinessProbe:
  tcpSocket:
    port: 5432
  initialDelaySeconds: 10
  periodSeconds: 10

# HPA: OFF by default (turning it on for a DB is rarely right)
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}

# ----- Postgres-specific knobs we added -----
auth:
  username: appuser
  password: "pasima"     # change in real use
  database: appdb

# ephemeral for now (no default StorageClass on your self-managed cluster)
persistence:
  enabled: false

